refactor: 버프 항목들을 게임 오브젝트로 옮김
- BuffSO.cs 파일로 생성함
- 에러가 발생함(체력 회복 버프 획득 시 게임이 멈춤, 이슈 생성 예정):
NullReferenceException: Object reference not set to an instance of an object
BuffController.OnTriggerEnter (UnityEngine.Collider other) (at Assets/Scripts/BuffController.cs:25)
- 포탑 스크립터블 오브젝트 스탯 수정
- 버프를 설정하기 위한 변수를 합연산 / 곱연산 값으로 나눔