fix(issue#61): 버그 해결 및 새로운 버그 발생
- 체력 회복 아이템을 먹으면 에러가 나오는 문제 해결함. 맵에 존재하는 모든 체력 회복 아이템 프리팹을 지우고 새로 넣는 방식으로 해결함.
- Map3에서 새로운 버그 발생:
NullReferenceException: Object reference not set to an instance of an object
MapCreateManager.OnGetMap (Map map) (at Assets/Scripts/Map/MapCreateManager.cs:62)
UnityEngine.Pool.ObjectPool`1[T].Get () (at <612ea0208cc847f49d539e6511ed3cd5>:0)
MapCreateManager.CreateMap () (at Assets/Scripts/Map/MapCreateManager.cs:45)
MapTrigger.OnTriggerStay (UnityEngine.Collider other) (at Assets/Scripts/Map/MapTrigger.cs:11)

close: issue#61