feat(map): 두번째 맵 제작 완료
- 두번째 맵(NewMap1)을 제작하고, prefab화 완료.
- 총알과 관련된 버그가 발생하기 시작함:
InvalidOperationException: Trying to release an object that has already been released to the pool.
UnityEngine.Pool.ObjectPool`1[T].Release (T element) (at <612ea0208cc847f49d539e6511ed3cd5>:0)
EnemyBullet.DestroyBullet () (at Assets/Scripts/Enemy/EnemyBullet.cs:50)
EnemyBullet.OnTriggerEnter (UnityEngine.Collider other) (at Assets/Scripts/Enemy/EnemyBullet.cs:38)